### ISSUE TITLE
Privacy policy

### ISSUE THREAD

**Issue by CedricBlns** [paulbijou/paulbijou.github.io#1]
Er is geen privacy policy???? Is dit het bewijs dat PRENEEL werkt voor de NSA = NASA zonder de A van ALKOOL ===> De maanlanding is FAEK! en verzonnen door BIG CARA

**Comment by RobbertH** [comment]
@CedricBlns voor fundamentele klachten kan je steeds de contact form invullen op onze website. Onze klantendienst zal uw aanvraag dan onmiddellijk verwerpen. Dank bij voorbaat.

**Comment by RobbertH** [comment]
Also: ik dacht dat ik deze repo private had gemaakt :p Bedankt voor de heads-up!
